services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - CORE_CONF_hadoop_http_cross_origin_enabled=true
      - CORE_CONF_hadoop_http_cross_origin_allowed_origins='*'
      - CORE_CONF_hadoop_http_cross_origin_allowed_methods=GET,POST,PUT,DELETE,HEAD,OPTIONS
      - CORE_CONF_hadoop_http_cross_origin_allowed_headers=X-Requested-With,Content-Type,Accept,Origin
    networks:
      - bigdata-net
    volumes:
      - namenode-data:/hadoop/dfs/name

  datanode-pc:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-pc
    hostname: datanode-pc
    ports:
      - "9864:9864"
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - CORE_CONF_hadoop_http_cross_origin_enabled=true
      - CORE_CONF_hadoop_http_cross_origin_allowed_origins='*'
      - CORE_CONF_hadoop_http_cross_origin_allowed_methods=GET,POST,PUT,DELETE,HEAD,OPTIONS
      - CORE_CONF_hadoop_http_cross_origin_allowed_headers=X-Requested-With,Content-Type,Accept,Origin
      - HDFS_CONF_dfs_http_cross_origin_enabled=true
      - HDFS_CONF_dfs_http_cross_origin_allowed_origins='*'
      - HDFS_CONF_dfs_http_cross_origin_allowed_methods=GET,POST,PUT,DELETE,HEAD,OPTIONS
      - HDFS_CONF_dfs_http_cross_origin_allowed_headers=X-Requested-With,Content-Type,Accept,Origin
    networks:
      - bigdata-net
    volumes:
      - datanode-pc-data:/hadoop/dfs/data
    depends_on:
      - namenode

  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - bigdata-net

  spark-worker-pc:
    image: apache/spark:3.5.3
    container_name: spark-worker-pc
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    networks:
      - bigdata-net
    depends_on:
      - spark-master

  jupyter-dev:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter-dev
    user: root
    ports:
      - "8889:8888"
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.py --IdentityProvider.token='' --ServerApp.password=''
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge

volumes:
  namenode-data:
  datanode-pc-data: